The ``0-add_integer`` module
======================

Using ``add_integer``
------------------


Importing the function from the module:
	>>> add_integer = __import__("0-add_integer").add_integer

Checking for module docstring:
	 >>> m = __import__("0-add_integer").__doc__
	 >>> len(m) > 1
	 True
Importing the function from the module:
>>> add_integer = import("0-add_integer").add_integer

Checking regular addition:
>>> add_integer(4, 5)
9

Checking positive with negative:
>>> add_integer(8, -6)
2

Checking negative with positive:
>>> add_integer(-3, 7)
4

Checking addition over multiple values:
>>> [add_integer(i, i * 3) for i in range(4)]
[0, 4, 8, 12]

Checking float with int:
>>> add_integer(6.9, 2)
8

Checking int with float:
>>> add_integer(10, 4.2)
14

Checking both float:
>>> add_integer(1.5, 2.6)
4

Checking for passed NaN:
>>> add_integer(float('nan'), 3)
Traceback (most recent call last):
...
ValueError: cannot convert float NaN to integer

Checking for passed inf:
>>> add_integer(5, float('inf'))
Traceback (most recent call last):
...
OverflowError: cannot convert float infinity to integer

Checking super long int:
>>> add_integer(999999999999999999999999999999, 5)
1000000000000000000000000000004

Checking non-number with number:
>>> add_integer("2", 4)
Traceback (most recent call last):
...
TypeError: a must be an integer

Checking number with non-number:
>>> add_integer(6, [1])
Traceback (most recent call last):
...
TypeError: b must be an integer

Checking non-number with non-number:
>>> add_integer({1}, "string")
Traceback (most recent call last):
...
TypeError: a must be an integer

Checking bool with number:
>>> add_integer(True, 3)
Traceback (most recent call last):
...
TypeError: a must be an integer

Checking number with bool:
>>> add_integer(5, False)
Traceback (most recent call last):
...
TypeError: b must be an integer

Checking no args:
>>> add_integer()
Traceback (most recent call last):
...
TypeError: add_integer() missing 2 required positional arguments: 'a' and 'b'

Checking one arg:
>>> add_integer(3)
Traceback (most recent call last):
...
TypeError: add_integer() missing 1 required positional argument: 'b'

Checking more than 2 args:
>>> add_integer(1, 2, 4)
Traceback (most recent call last):
...
TypeError: add_integer() takes 2 positional arguments but 3 were given
